# ~/.config/sway/colors.inc.template

# ~/.config/themes/sway-colors.inc.template
set $bg #1F1F20
set $fg #E8E8E8
set $ac #724A55

client.focused          $ac     $bg     $fg  $ac  $ac
client.focused_inactive $bg     $bg     $fg  $bg  $bg
client.unfocused        $bg     $bg     $fg  $bg  $bg
client.urgent           $ac     $ac     $ac  $ac  $ac
client.placeholder      $bg     $bg     $fg  $bg  $bg
